apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-eta-deploy
  labels:
    app: insurance-eta-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insurance-eta-deploy
  template:
    metadata:
      labels:
        app: insurance-eta-deploy
    spec:
      containers:
      - name: insurance-eta-deploy
        image: pratima30/insurance-eta-deploy
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-eta-np-service
  labels:
    app: insurance-eta-deploy
spec:
  selector:
    app: insurance-eta-deploy

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
